from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch

from anomalib.data import Folder, PredictDataset
from anomalib.engine import Engine
from anomalib.models import Patchcore

from harting_anomaly.core.config import CONFIG
from harting_anomaly.data.catalog import normalize_identifier


def collect_scores(predictions) -> list[float]:
    scores: list[float] = []
    for prediction in predictions or []:
        value = prediction.pred_score
        if value is None:
            continue
        array = value.detach().cpu().numpy().reshape(-1)
        scores.extend(float(x) for x in array)
    return scores


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--product", required=True)
    parser.add_argument("--view", required=True)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--batch-size", type=int, default=4)
    args = parser.parse_args()

    product = normalize_identifier(args.product)
    view = normalize_identifier(args.view)
    dataset_root = CONFIG.paths.prepared_data_root / product / view
    if not dataset_root.exists():
        raise FileNotFoundError(
            f"Prepared dataset not found: {dataset_root}\n"
            "Run prepare_demo_dataset.py first."
        )

    model_root = CONFIG.paths.patchcore_models_root / product / view
    model_root.mkdir(parents=True, exist_ok=True)

    image_size = (256, 256)

    datamodule = Folder(
        name=f"{product}__{view}",
        root=dataset_root,
        normal_dir="train/good",
        normal_test_dir="val/good",
        train_batch_size=args.batch_size,
        eval_batch_size=args.batch_size,
        num_workers=args.num_workers,
        normal_split_ratio=0.0,
        seed=42,
    )

    model = Patchcore(
        backbone="wide_resnet50_2",
        layers=("layer2", "layer3"),
        pre_trained=True,
        coreset_sampling_ratio=0.10,
        num_neighbors=9,
        post_processor=False,
        evaluator=False,
        visualizer=False,
    )

    engine = Engine(
        default_root_dir=model_root / "anomalib_runs",
        accelerator="auto",
        devices=1,
        logger=False,
    )

    print(f"Training PatchCore: {product} / {view}")
    print(f"Dataset: {dataset_root}")

    engine.fit(model=model, datamodule=datamodule)

    # Locate the checkpoint generated by Anomalib.
    checkpoints = sorted(
        (model_root / "anomalib_runs").rglob("*.ckpt"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not checkpoints:
        raise RuntimeError("Anomalib training completed but no .ckpt file was found.")

    source_ckpt = checkpoints[0]
    target_ckpt = model_root / "model.ckpt"
    target_ckpt.write_bytes(source_ckpt.read_bytes())

    # Calibrate a prototype threshold on known-good validation images.
    validation_dir = dataset_root / "val" / "good"
    validation_dataset = PredictDataset(
        path=validation_dir,
        image_size=image_size,
    )

    predictions = engine.predict(
        model=model,
        dataset=validation_dataset,
        return_predictions=True,
    )
    scores = collect_scores(predictions)
    if not scores:
        raise RuntimeError("No validation scores were produced.")

    quantile = 0.995
    threshold = float(np.quantile(np.asarray(scores), quantile))

    metadata = {
        "product": product,
        "view": view,
        "backbone": "wide_resnet50_2",
        "layers": ["layer2", "layer3"],
        "pre_trained": True,
        "coreset_sampling_ratio": 0.10,
        "num_neighbors": 9,
        "image_size": list(image_size),
        "threshold": threshold,
        "threshold_method": "validation_quantile",
        "threshold_quantile": quantile,
        "validation_count": len(scores),
        "validation_score_min": float(np.min(scores)),
        "validation_score_max": float(np.max(scores)),
        "validation_score_mean": float(np.mean(scores)),
    }

    (model_root / "model.json").write_text(
        json.dumps(metadata, indent=2),
        encoding="utf-8",
    )

    print("\nTraining complete")
    print(f"Checkpoint : {target_ckpt}")
    print(f"Metadata   : {model_root / 'model.json'}")
    print(f"Val images : {len(scores)}")
    print(f"Threshold  : {threshold:.6f}")


if __name__ == "__main__":
    main()